### ISSUE TITLE
Is there a timeout?

### ISSUE THREAD

**Issue by TheHandyUser** [Maxisthemoose/example-discord-battleship-bot#1]

**Comment by Maxisthemoose** [comment]
For?...

**Comment by TheHandyUser** [comment]
After which it automatically stops the game?

**Comment by Maxisthemoose** [comment]
What do you mean

**Comment by TheHandyUser** [comment]
I mean how long does the game take to expire?

**Comment by TheHandyUser** [comment]
If the users dont respong in some time the game will stop right or wrong, if yes then how long

**Comment by Maxisthemoose** [comment]
It doesn't, and this project was abandoned a while ago, so I probably wont be adding anything like that, sorry

**Comment by TheHandyUser** [comment]
Mind if i fork it?

**Comment by Maxisthemoose** [comment]
Of course, fork the actual project though, not the example bot

**Comment by TheHandyUser** [comment]
Ok tnx
